[package]
name = "note-block-forge-lib"
version = "0.1.0"
authors = ["Possseidon <xpossseidon@gmail.com>"]
edition = "2021"
description = "Library for NoteBlockForge"
readme = "README.md"
repository = "https://github.com/Possseidon/note-block-forge"
license = "MIT"
keywords = ["minecraft", "note-block", "music", "library", "audio"]
categories = ["multimedia::audio", "games"]

[dependencies]
derive_more.workspace = true
enum-map.workspace = true
midir.workspace = true
rodio.workspace = true
serde.workspace = true
